Imports System
Imports System.Threading
Imports System.Globalization
Imports System.Windows.Forms
'  All designed code is stored in the autogenerated partial
'  class called Recipe07-13.Designer.vb.  You can see this
'  file by selecting "Show All Files" in solution explorer.
Partial Public Class Recipe07_13

    Public Shared Sub Main()

        Thread.CurrentThread.CurrentUICulture = New CultureInfo("fr")
        Application.Run(New Recipe07_13)

    End Sub
    Private Sub Recipe07_13_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load

    End Sub

End Class
