'  All designed code is stored in the autogenerated partial
'  class called Recipe07-19.Designer.vb.  You can see this
'  file by selecting "Show All Files" in solution explorer.
Partial Public Class Recipe07_19

End Class
