Imports System
Imports System.Windows.Forms
Imports System.Xml
Imports System.IO
'  All designed code is stored in the autogenerated partial
'  class called XmlTreeDisplay.Designer.vb. You can see this
'  file by selecting Show All Files in Solution Explorer.
Partial Public Class XmlTreeDisplay

    Private Sub cmdLoad_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdLoad.Click

        '  Clear the tree.
        Dim doc As New XmlDocument

        Try
            doc.Load(txtXmlFile.Text)

            '  Populate the TreeView.
            ConvertXmlNodeToTreeNode(doc, treeXml.Nodes)

            '  Expand all nodes.
            treeXml.Nodes(0).ExpandAll()
        Catch ex As Exception
            MessageBox.Show(ex.Message)
        End Try

    End Sub
    Private Sub ConvertXmlNodeToTreeNode(ByVal thisXmlNode As XmlNode, ByVal treeNodes As TreeNodeCollection)

        '  Add a TreeNode node that represents this XmlNode.
        Dim newTreeNode As TreeNode = treeNodes.Add(thisXmlNode.Name)

        '  Customize the TreeNode text based on the XmlNode
        '  type and content.
        Select Case thisXmlNode.NodeType
            Case XmlNodeType.ProcessingInstruction
                newTreeNode.Text = thisXmlNode.Value
            Case XmlNodeType.XmlDeclaration
                newTreeNode.Text = "<?" & thisXmlNode.Name & " " & thisXmlNode.Value & "?>"
            Case XmlNodeType.Element
                newTreeNode.Text = "<" & thisXmlNode.Name & ">"
            Case XmlNodeType.Attribute
                newTreeNode.Text = "ATTRIBUTE: " & thisXmlNode.Name
            Case XmlNodeType.Text
                newTreeNode.Text = thisXmlNode.Value
            Case XmlNodeType.CDATA
                newTreeNode.Text = thisXmlNode.Value
            Case XmlNodeType.Comment
                newTreeNode.Text = "<!--" & thisXmlNode.Value & "-->"
        End Select

        '  Call this routine recursively for each attribute.
        '  (XmlAttribute is a subclass of XmlNode.)
        If Not thisXmlNode.Attributes Is Nothing Then
            For Each attribute As XmlAttribute In thisXmlNode.Attributes
                ConvertXmlNodeToTreeNode(attribute, newTreeNode.Nodes)
            Next
        End If

        '  Call this routine recursively for each child node.
        '  Typically, this child node represents a nested element
        '  or element content.
        For Each childNode As XmlNode In thisXmlNode.ChildNodes
            ConvertXmlNodeToTreeNode(childNode, newTreeNode.Nodes)
        Next

    End Sub
    Private Sub XmlTreeDisplay_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        txtXmlFile.Text = Path.Combine(Application.StartupPath, "..\..\ProductCatalog.xml")

    End Sub

End Class
