Imports System
Imports System.Windows.Forms
Imports QuartzTypeLib
'  All designed code is stored in the autogenerated partial
'  class called Recipe08-11.Designer.vb.  You can see this
'  file by selecting "Show All Files" in solution explorer.
Partial Public Class Recipe08_11

    Private Sub cmdOpen_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdOpen.Click

        '  Allow the user to choose a file.
        Dim openDialog As New OpenFileDialog

        openDialog.Filter = "Media FIles|*.wav;*.mp3;*.mp2;*.wma|All Files|*.*"

        If openDialog.ShowDialog = Windows.Forms.DialogResult.OK Then
            '  Access the IMediaControl interface.
            Dim graphManager As New QuartzTypeLib.FilgraphManager
            Dim mc As QuartzTypeLib.IMediaControl = DirectCast(graphManager, QuartzTypeLib.IMediaControl)

            '  Specify the file.
            mc.RenderFile(openDialog.FileName)
            
            Try
                mc.Run()
            Catch ex As Exception
                MessageBox.Show("An error occurred while playing media.")
            Finally
                '  Destroy the COM object (QuartzTypeLib) that we are using.
                System.Runtime.InteropServices.Marshal.ReleaseComObject(graphManager)
            End Try

        End If

    End Sub

End Class
